import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const WIDTHS = [400, 800, 1200] as const;

export interface ImageMeta {
  width: number;
  height: number;
  srcset: string;
}

// Reads native dimensions and builds a `srcset` from whichever responsive
// variants (generated by scripts/generate-responsive-images.mjs) exist on
// disk. Safe to call from `.astro` frontmatter: these landing pages are
// statically prerendered, so this runs once per photo at `astro build` time,
// not per request.
export async function getImageMeta(publicPath: string): Promise<ImageMeta> {
  const fsPath = path.join(process.cwd(), "public", publicPath);
  const { width, height } = await sharp(fsPath).metadata();
  if (!width || !height) {
    throw new Error(`getImageMeta: could not read dimensions for ${publicPath}`);
  }
  const base = publicPath.replace(/\.webp$/, "");
  const srcsetParts = WIDTHS.filter(
    (w) => w < width && existsSync(path.join(process.cwd(), "public", `${base}-${w}w.webp`)),
  ).map((w) => `${base}-${w}w.webp ${w}w`);
  srcsetParts.push(`${publicPath} ${width}w`);
  return { width, height, srcset: srcsetParts.join(", ") };
}
